### ISSUE TITLE
Version 0.9 defaults to private; even though the code is set to public-read

### ISSUE THREAD

**Issue by bzerangue** [symphonists/s3upload_field#23]
I am using Symphony 2.3.6 on a very large site. After upgrading from version 0.7 to 0.9, every time I would upload something, it would mark it as private. It seemed to be ignoring the public-read (default setting)...

<https://github.com/symphonists/s3upload_field/blob/master/fields/field.s3upload.php#L378>

Anyway, I tried re-installing it and same issue. I moved back to version 0.8.1 and that corrected the issue. But that version of the extension was before the new S3 library was added to this extension. 

It looks as if version 0.9 of the extension isn't recognizing the public-read ACL (or is just plain ignoring it, and setting it as private (Owner access only).

**Comment by TheJester12** [comment]
This was fixed. https://github.com/symphonists/s3upload_field/pull/25

**Comment by nitriques** [comment]
Thanks @TheJester12 !
